=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/main/resources/mods.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.loc.gov/mods/v3"
  xmlns:self="http://www.loc.gov/mods/v3" elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <xs:element name="modsCollection">
    <xs:complexType>
      <xs:all>
        <xs:element name="mods" type="self:mods" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="mods">
    <xs:sequence>
      <xs:element name="identifier" type="self:hbzIdentifier" minOccurs="1" maxOccurs="1" />
      <xs:element name="originInfo" type="self:originInfo" minOccurs="1" maxOccurs="1" />
      <xs:element name="genre" type="self:genre" minOccurs="1" maxOccurs="1" />
      <xs:element name="note" type="self:note" minOccurs="1" maxOccurs="unbounded" />
      <xs:element name="location" type="self:location" minOccurs="1" maxOccurs="1" />
      <xs:element name="typeOfResource" type="self:typeofResource" minOccurs="1" maxOccurs="1"/>
      <xs:element name="subject" type="self:subject" minOccurs="1" maxOccurs="1" />
      <xs:element name="name" type="self:name" minOccurs="1" maxOccurs="unbounded" />
      <xs:element name="recordInfo" type="self:recordInfo" minOccurs="1" />
      <xs:element name="physicalDescription" type="self:physicalDescription" minOccurs="1" />
      <xs:element name="titleInfo" type="self:titleInfo" minOccurs="1" />
    </xs:sequence>
    <xs:attribute name="version">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="3.5" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="ID">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="merian\d{4}topographia" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="titleInfo">
    <xs:sequence>
      <xs:element name="title">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="physicalDescription">
    <xs:sequence>
      <xs:element name="extent">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="form" type="self:form">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="form">
    <xs:simpleContent>
      <xs:extension base="self:formValue">
        <xs:attribute name="authority" use="optional">
          <xs:simpleType>
            <xs:restriction base="xs:string"/>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="formValue">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="typeofResource">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="recordInfo">
    <xs:sequence>
      <xs:element name="recordContentSource">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="DE-605" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="location">
    <xs:sequence>
      <xs:element name="physicalLocation">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="name">
    <xs:sequence>
      <xs:element name="namePart">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="subject">
    <xs:sequence>
      <xs:element name="topic">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="note">
    <xs:simpleContent>
      <xs:extension base="self:noteValue">
        <xs:attribute name="type" use="optional">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="statement of responsibility"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="noteValue">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="genre">
    <xs:simpleContent>
      <xs:extension base="self:genreValue">
        <xs:attribute name="authority">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="marcgt"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="genreValue">
    <xs:restriction base="xs:string">
      <xs:enumeration value="book" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="hbzIdentifier">
    <xs:simpleContent>
      <xs:extension base="self:hbzIdentifierValue">
        <xs:attribute name="type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="HBZ" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="originInfo">
    <xs:sequence>
      <xs:element name="dateIssued">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="place" type="self:place">
      </xs:element>
      <xs:element name="publisher">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="[Meriansche Erben]" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="hbzIdentifierValue">
    <xs:restriction base="xs:string">
      <xs:pattern value="HT\d+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="placeTermValue">
    <xs:restriction base="xs:string">
      <xs:enumeration value="[Frankfurt, Main]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="place">
    <xs:all>
      <xs:element name="placeTerm">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="self:placeTermValue">
              <xs:attribute name="type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

</xs:schema>

=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/main/resources/modsFiles/ah232-3_HT018907295_Moguntiensis_Trevirensis_1690.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2023 René Ackels
Permission is hereby granted, free of charge, to any person obtaining

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>. -->
<mods:modsCollection xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mods="http://www.loc.gov/mods/v3" xsi:schemaLocation="http://www.loc.gov/mods/v3 ../mods.xsd" >
  <mods:mods version="3.5" ID="merian1690topographia">
    <mods:identifier type="HBZ">HT018907295</mods:identifier>
    <mods:originInfo>
      <mods:dateIssued>1690</mods:dateIssued>
      <mods:place>
        <mods:placeTerm type="text">[Frankfurt, Main]</mods:placeTerm>
      </mods:place>
      <mods:publisher>[Meriansche Erben]</mods:publisher>
    </mods:originInfo>
    <mods:genre authority="marcgt">book</mods:genre>
    <mods:note type="statement of responsibility">An Tag gegeben dúrch Matth: Merian ; [Martin Zeiller]</mods:note>
    <mods:note>Bevorzugter Titel: Topographia Archiepiscopatuum Moguntinensis, Trevirensis et Coloniensis</mods:note>
    <mods:note>Bibliographischer Nachweis: Wüthrich: Das druckgraphische Werk von Matthaeus Merian d. Ae., Band 4 (1996), Nummer 31</mods:note>
    <mods:note>Textverfasser ermittelt</mods:note>
    <mods:note>Hinweise zur Ausgabe (nach Wüthrich): 3. Ausgabe Frankfurt, Meriansche Erben</mods:note>
    <mods:note>Erscheinungsjahr nach Wüthrich: datiert 1646, effektiv um 1690</mods:note>
    <mods:note>Blatt M4, verso unbedruckt</mods:note>
    <mods:note>Seite 3 mit Hozschnittleiste "Vase und Rebhühner"</mods:note>
    <mods:note>Die Panoramaansicht von Mainz mit großem vertikalem Riß, 8 cm vom linken Bildrand aus. - Im Register sind von "Königsberg" bis "Kyll" die Anfangsmajuskeln K in Schwabacher- statt in Fraktur-Lettern gesetzt.</mods:note>
    <mods:note>Kupfertitel (erstes Blatt). - Reihenfolge der Kupfer siehe Bindeanweisung (43 Nummern). Die Karte des Eichsfelds fehlt im Kupferverzeichnis und im Band.</mods:note>
    <mods:note>Format: groß-4°</mods:note>
    <mods:note>FEI-Fingerprint nach dem Exemplar der Universitätsbibliothek Trier</mods:note>
    <mods:note>hbz Verbund-ID: HT018907295</mods:note>
    <mods:location>
      <mods:physicalLocation>DE-385: https://lobid.org/organisations/DE-385</mods:physicalLocation>
    </mods:location>
    <mods:typeOfResource>text</mods:typeOfResource>
    <mods:subject>
      <mods:topic>vornehmsten Städte Plätze den Erzbistümern Mainz Köln</mods:topic>
    </mods:subject>
    <mods:name>
      <mods:namePart>Merian, Matthaeus, der Ältere</mods:namePart>
    </mods:name>
    <mods:name>
      <mods:namePart>Zeiller, Martin</mods:namePart>
    </mods:name>
    <mods:name>
      <mods:namePart>Frankfurt am Main</mods:namePart>
    </mods:name>
    <mods:recordInfo>
      <mods:recordContentSource>DE-605</mods:recordContentSource>
    </mods:recordInfo>
    <mods:physicalDescription>
      <mods:extent>95 Seiten, 9 ungezählte Seiten, 64 ungezählte Blätter Bildtafeln (zum Teil gefaltet) ; Illustrationen, Karten ; 4°</mods:extent>
      <mods:form authority="marcform">print</mods:form>
    </mods:physicalDescription>
    <mods:titleInfo>
      <mods:title>Topographia Archiepiscopatuvm Moguntinensis, Treuirensis, et Coloniensis, Das ist Beschreibúng der Vornembsten Stätt vnd Plätz, in denen Ertzbistúmen Maÿntz, Trier, vnd Cöln.</mods:title>
    </mods:titleInfo>
  </mods:mods>
</mods:modsCollection>

=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/test/resources/testcase2/modsFiles/Testmods.xml
<?xml version="1.0" encoding="UTF-8"?>
<mods:modsCollection xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mods="http://www.loc.gov/mods/v3" xsi:schemaLocation="http://www.loc.gov/mods/v3 ../../mods.xsd" >
  <mods:mods version="3.5" ID="merian1690topographia">
      <mods:identifier type="HBZ">HT018907295</mods:identifier>
      <mods:originInfo>
          <mods:dateIssued>1690</mods:dateIssued>
          <mods:place>
              <mods:placeTerm type="text">[Frankfurt, Main]</mods:placeTerm>
          </mods:place>
          <mods:publisher>[Meriansche Erben]</mods:publisher>
      </mods:originInfo>
      <mods:genre authority="marcgt">book</mods:genre>
      <mods:note type="statement of responsibility">Matthäus Merian</mods:note>
      <mods:note>Dies ist eine zusätzliche Testnotiz</mods:note>
      <mods:location>
          <mods:physicalLocation>DE-385: https://lobid.org/organisations/DE-385</mods:physicalLocation>
      </mods:location>
      <mods:typeOfResource>text</mods:typeOfResource>
      <mods:subject>
          <mods:topic>irgendwelche schönen Städte</mods:topic>
      </mods:subject>
      <mods:name>
          <mods:namePart>Gandalf, der Weiße</mods:namePart>
      </mods:name>
      <mods:name>
          <mods:namePart>noch ein, name Part</mods:namePart>
      </mods:name>
      <mods:recordInfo>
          <mods:recordContentSource>DE-605</mods:recordContentSource>
      </mods:recordInfo>
      <mods:physicalDescription>
          <mods:extent>3 Seiten, 0 ungezählte Seiten, 0 ungezählte Blätter Bildtafeln (zum Teil gefaltet) ; Illustrationen, Karten ; 4°</mods:extent>
          <mods:form authority="marcform">print</mods:form>
      </mods:physicalDescription>
      <mods:titleInfo>
          <mods:title>Trier und Köln.</mods:title>
      </mods:titleInfo>
  </mods:mods>
</mods:modsCollection>

=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/main/resources/modsFiles/ah232-1_HT018899501_Helvetiae_Rhaetiae_1655.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2023 René Ackels

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>. -->
<mods:modsCollection xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd">
  <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/mods/v3 ../mods.xsd" version="3.5" ID="merian1655topographia">
    <mods:genre authority="marcgt">book</mods:genre>
    <mods:name>
      <mods:namePart>Merian, Matthaeus, der Ältere</mods:namePart>
    </mods:name>
    <mods:name>
      <mods:namePart>Zeiller, Martin</mods:namePart>
    </mods:name>
    <mods:name>
      <mods:namePart>Frankfurt am Main</mods:namePart>
    </mods:name>
    <mods:originInfo>
      <mods:edition>In dieser andern Edition mit sonderm Fleiß durchgangen, und von vorigen Fehlern corrigirt/ vermehrt und gebessert.</mods:edition>
      <mods:dateIssued>1655</mods:dateIssued>
      <mods:publisher>Zum Truck verlegt von denen Merianischen Erben</mods:publisher>
      <mods:place>
        <mods:placeTerm type="text">Franckfurt am Mayn</mods:placeTerm>
      </mods:place>
    </mods:originInfo>
    <mods:identifier type="HBZ">HT018899501</mods:identifier>
    <mods:location>
      <mods:physicalLocation> ah232-1 99 (Raraausleihe)DE-385: https://lobid.org/organisations/DE-385</mods:physicalLocation>
    </mods:location>
    <mods:subject>
      <mods:topic>Eidgenossenschaft Graubünden Orten</mods:topic>
    </mods:subject>
    <mods:typeOfResource>text</mods:typeOfResource>
    <mods:physicalDescription>
      <mods:form authority="marcform">print</mods:form>
      <mods:extent>90 Seiten, 6 ungezählte Seiten, 2 ungezählte Blätter, 137 ungezählte Blätter Bildtafeln (zum Teil gefaltet) ; Illustrationen, Karten ; 4°</mods:extent>
    </mods:physicalDescription>
    <mods:recordInfo>
      <mods:recordContentSource>DE-605</mods:recordContentSource>
    </mods:recordInfo>
    <mods:titleInfo>
      <mods:title>M.Z. Topographia Helvetiæ, Rhætiæ, Te Valesiæ</mods:title>
      <mods:subTitle>Das ist/ Beschreibung und eigentliche Abbildung der vornehmsten Städte und Plätze in der Hochlöblichen Eydgenoßschafft, Graubündten, Wallis/ und etlicher zugewandten Orthen</mods:subTitle>
    </mods:titleInfo>
    <mods:note type="statement of responsibility">In Truck gegeben v. Verlegt Durch Matthæum Meriān</mods:note>
    <mods:note>Bevorzugter Titel: Topographia Helvetiae, Rhaetiae et Valesiae</mods:note>
    <mods:note>Bibliographischer Nachweis: Wüthrich, Lucas Heinrich: Das druckgraphische Werk von Matthaeus Merian d. Ae., Band 4 (1996), Nummer 6; nicht bei Schuchhard</mods:note>
    <mods:note>Neuer Drucktitel</mods:note>
    <mods:note>Verantwortlichkeitsangabe: Matthaeus Merian ist im Kupfertitel genannt. - Martin Zeiller (M.Z.) ist Textverfasser, von Matthaeus Merian stammen die Illustrationen (Kupfer)</mods:note>
    <mods:note>Hinweise zur Ausgabe (nach Wüthrich): 3. deutsche Ausgabe, Frankfurt (Matthaeus Merians Erben)</mods:note>
    <mods:note>Vorlageform der Veröffentlichungsangabe: Franckfurt am Mayn/ Zum Truck verlegt von denen Merianischen Erben. Jm Jahr MDCLIV.</mods:note>
    <mods:note>Erscheinungsjahr nach Wüthrich: datiert 1654, effektiv später, nach 1655</mods:note>
    <mods:note>Kupfertitel: Topographia Heluetiæ, Rhætiæ et Valesiæ, Das ist Beschreibung vnd Eigentliche Abbildûng der Vornembsten Stätte vnd Plätz in der Hochlöblichen Eydgnoßschafft, Grawbündten, Walliß, vnd etlicher Zugewanten Orten</mods:note>
    <mods:note>Kupfertitel. - Reihenfolge der Kupfer siehe Bindeanweisung</mods:note>
    <mods:note>Erscheinungsjahr Kupfertitel: M.DC.XLII.</mods:note>
    <mods:note>Umfangsangabe: Seiten 60-62 als 40-42, Seite 82 als 28, Seite 87 als 69 paginiert</mods:note>
    <mods:note>Format: groß-4°</mods:note>
    <mods:note>Gedruckter Titel ohne Verlagssignet von Merian. - Zierleiste auf Seite 5 und 10 und zu Beginn des Registers mit Röslein</mods:note>
    <mods:note>FEI-Fingerprint nach dem Exemplar der Universitätsbibliothek Trier</mods:note>
    <mods:note>hbz Verbund-ID: HT018899501</mods:note>
  </mods:mods>
</mods:modsCollection>
