=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/main/resources/xml_OCR_Output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15"
  xmlns:self="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <!-- xsi:schemaLocation="http://www.loc.gov/mods/v3 xml_OCR_Output.xsd" -->

  <!-- targetNamespace="http://www.loc.gov/mods/v3" -->
  <xs:element name="PcGts">
    <xs:complexType>
      <xs:all>
        <xs:element name="Metadata" type="self:MetadataType" />
        <xs:element name="Page" type="self:PageType" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="PageType">
    <xs:sequence>
      <xs:element name="ReadingOrder" type="self:ReadingOrderType" />
      <xs:element name="TextRegion" type="self:TextRegionType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="imageFilename" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="imageHeight" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="imageWidth" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:complexType name="TextRegionType">
    <xs:sequence>
      <xs:element name="Coords" type="self:CoordsType" />
      <xs:element name="TextLine" type="self:TextLineType"  minOccurs="0"
      maxOccurs="unbounded" />
      <xs:element name="TextEquiv" type="self:TextEquivType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="r\d+" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="orientation" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TextLineType">
    <xs:sequence>
      <xs:element name="Coords" type="self:CoordsType" />
      <xs:element name="TextEquiv" type="self:TextEquivType" minOccurs="1"
      maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="l\d+" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="CoordsType">   
    <xs:attribute name="points" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+(,\d+ \d+)*,\d+"/>
          <!-- <xs:pattern value="^\d+(,\d+ \d+)*,\d+"/> -->
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:complexType name="TextEquivType">   
    <xs:sequence>
      <xs:element name="Unicode" />
    </xs:sequence>
    <xs:attribute name="index" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="ReadingOrderType">
    <xs:all>
      <xs:element name="OrderedGroup" type="self:OrderedGroupType" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="OrderedGroupType">
    <xs:sequence>
      <xs:element name="RegionRefIndexed" type="self:RegionRefIndexedType" minOccurs="1"
        maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id">
      <xs:simpleType>
        <xs:restriction base="xs:string">
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="RegionRefIndexedType">
    <xs:attribute name="index" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d*" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="regionRef" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="r\d*" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:complexType name="MetadataType">
    <xs:all>
      <xs:element name="Creator" type="self:CreatorType" />
      <xs:element name="Created" type="self:CreatedType" />
      <xs:element name="LastChange" type="self:LastChangeType" />
      <xs:element name="Comments" type="self:CommentsType" />
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="CreatorType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="CreatedType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}" />
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="LastChangeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CommentsType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  
</xs:schema>

=== Universitatsbibliothek-Trier/OCR-To-TEI/OCR-To-TEI/src/test/resources/testcase1/ocrOutputFiles/002.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PcGts xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15 ../../xml_OCR_Output.xsd">
  <Metadata>
    <Creator/>
    <Created>2021-11-11T11:11:11</Created>
    <LastChange>2023-11-11T11:11:11</LastChange>
    <Comments/>
  </Metadata>
  <Page imageFilename="0012.png" imageHeight="6502" imageWidth="3870">
    <ReadingOrder>
      <OrderedGroup id="g3">
        <RegionRefIndexed index="0" regionRef="r2"/>
        <RegionRefIndexed index="1" regionRef="r3"/>
        <RegionRefIndexed index="2" regionRef="r4"/>
        <RegionRefIndexed index="3" regionRef="r5"/>
        <RegionRefIndexed index="4" regionRef="r6"/>
      </OrderedGroup>
    </ReadingOrder>
    <ImageRegion id="r1">
      <Coords points="381,340 381,1176 3569,1176 3569,340"/>
    </ImageRegion>
    <TextRegion id="r2" orientation="0.25" type="paragraph">
      <Coords points="2312,2673"/>
      <TextLine id="l1">
        <Coords points="3669,2837"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 1 TextRegion 1 Seite 2 Zeile 1</Unicode>
        </TextEquiv>
        <TextEquiv index="1">
          <Unicode>Diese Zeile ist die gleiche wie oben?</Unicode>
        </TextEquiv>
      </TextLine>
      <TextLine id="l2">
        <Coords points="3691,2547"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 2 TextRegion 1 Seite 2 Zeile 2</Unicode>
        </TextEquiv>
      </TextLine>
      <TextLine id="l3">
        <Coords points="1975,4849"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 3 TextRegion 1 Seite 2 Zeile 3</Unicode>
        </TextEquiv>
      </TextLine>
      <TextLine id="l4">
        <Coords points="1975,4849"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 4 TextRegion 1 Seite 2 Zeile 4</Unicode>
        </TextEquiv>
      </TextLine>
      <TextEquiv>
        <Unicode/>
      </TextEquiv>
    </TextRegion>
    <TextRegion id="r3" orientation="0.25" type="paragraph">
      <Coords points="2312,2673"/>
      <TextLine id="l1">
        <Coords points="3669,2837"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 5 TextRegion 2 Seite 2 Zeile 1</Unicode>
        </TextEquiv>
      </TextLine>
    </TextRegion>
    <TextRegion id="r4" type="drop-capital">
      <Coords points="2312,2673"/>
      <TextLine id="l1">
        <Coords points="3669,2837"/>
        <TextEquiv index="0">
          <Unicode>G</Unicode>
        </TextEquiv>
      </TextLine>
    </TextRegion>
    <TextRegion id="r5" orientation="0.25" type="paragraph">
      <Coords points="2312,2673"/>
      <TextLine id="l1">
        <Coords points="3669,2837"/>
        <TextEquiv index="0">
          <Unicode>esamtzeile: 6 TextRegion 3 Seite 2 Zeile 1</Unicode>
        </TextEquiv>
      </TextLine>
    </TextRegion>
    <TextRegion id="r6" orientation="0.25" type="paragraph">
      <Coords points="511,1387"/>
      <TextLine id="l1">
        <Coords points="511,1387"/>
        <TextEquiv index="0">
          <Unicode>Gesamtzeile: 7 TextRegion 4 Seite 2 Zeile 1</Unicode>
        </TextEquiv>
      </TextLine>
    </TextRegion>
    <TextRegion id="r7" type="catch-word">
      <Coords points="3034,5875 3034,5580 3635,5580 3635,5875"/>
      <TextEquiv>
        <Unicode>Kustode2</Unicode>
      </TextEquiv>
    </TextRegion>
    <TextRegion id="r8" type="signature-mark">
      <Coords points="2257,5927 2257,5575 2649,5575 2649,5927"/>
      <TextEquiv>
        <Unicode>Bogensignatur2</Unicode>
      </TextEquiv>
    </TextRegion>
    <TextRegion id="r9" type="page-number">
      <Coords points="1938,330 1938,181 2005,181 2059,181 2059,330"/>
      <TextEquiv>
        <Unicode>3</Unicode>
      </TextEquiv>
    </TextRegion>
    <TextRegion id="r10" type="header">
      <Coords points="2257,5927 2257,5575 2649,5575 2649,5927"/>
      <TextEquiv>
        <Unicode>HeaderSeite2</Unicode>
      </TextEquiv>
    </TextRegion>
  </Page>
</PcGts>
